### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by bionade24**
# Pull Requests

If you are submitting a pull request, please read https://wiki.audiocity.serious/wiki/GitHub_Pull_Requests

### CODE REVIEW

**Comment by fliiiix** [comment]
lol

**Comment by davidak** [comment]
The README  says:

>Please open an issue if you're interested in becoming a maintainer for this project!

but issues are disabled. So i comment here.

There is one popular fork that is maintained, but looks for collaborators:

https://github.com/cookiengineer/audacity
https://fosspost.org/audacity-fork-needs-help/

I suggest you archive this repo, add a link to that fork and contribute there if you want. It does not make sense to maintain multiple forks with the same goal.

Thanks for your efforts defending free software!

**Comment by makefu** [comment]
@fliiiix @bionade24 i think we can safely merge this PR. lets hope i will not need to manually merge anything in the future!

**Comment by fliiiix** [comment]
>  It does not make sense to maintain multiple forks with the same goal.

This implies that we have any intention to maintain this fork which is not true.
This fork only exists for the name.

Maybe we should make that more clear in the readme and link to a actually fork :D 

(Also I can not do anything probably because I am only a member of the org)

**Comment by makefu** [comment]
@fliiiix with all the drama around audacity you are probably right. let provide you the permissions

**Pull request merged**
